
# Undo mangling of path from path_helper in /etc/zprofile
# add unique paths from PATH to FIXED_PATH and replace PATH with FIXED_PATH
if [ -n "$FIXED_PATH" ]; then
    FIXED_PATH=:$FIXED_PATH:;
    PATH=$PATH:
    while [ -n "$PATH" ]; do
        x=${PATH%%:*}  # the first remaining entry

        case $FIXED_PATH in
            *:$x:*)
                ;;  # already there
            *)
                FIXED_PATH=$FIXED_PATH$x:
                ;;  # not there yet
        esac
        PATH=${PATH#*:}
    done
    PATH=${FIXED_PATH:1:-1}

    unset FIXED_PATH x
    export PATH
fi
